/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Frames;

import static Frames.MainFrame.ContentPanel;
import java.awt.Color;
import javax.swing.JOptionPane;
import java.sql.*;
import java.awt.event.*;
import javax.swing.JButton;

/**
 *
 * @author RSSH
 */
public class ContentPane extends javax.swing.JPanel {

    /**
     * Creates new form ContentPane
     */
    public ContentPane() {
        initComponents();
        lblID.setVisible(false);
        Important.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDID = new javax.swing.JLabel();
        lblDueDate = new javax.swing.JLabel();
        lblCategoryName = new javax.swing.JLabel();
        lblDueTime = new javax.swing.JLabel();
        lblID = new javax.swing.JLabel();
        btnComplete = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        Important = new javax.swing.JLabel();
        Completed = new javax.swing.JLabel();
        btnDelete = new javax.swing.JButton();
        btnComplete1 = new javax.swing.JButton();
        btnComplete2 = new javax.swing.JButton();

        setBackground(new java.awt.Color(116, 185, 255));
        setPreferredSize(new java.awt.Dimension(700, 100));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        lblDID.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        lblDID.setText("ID");

        lblDueDate.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        lblDueDate.setText("Room");

        lblCategoryName.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        lblCategoryName.setText("Name");

        lblDueTime.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        lblDueTime.setText("Location");

        lblID.setText("ID");

        btnComplete.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        btnComplete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/tickmark.png"))); // NOI18N
        btnComplete.setBorder(null);
        btnComplete.setBorderPainted(false);
        btnComplete.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnComplete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompleteActionPerformed(evt);
            }
        });

        btnDelete.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Dellete-Small.png"))); // NOI18N
        btnDelete.setBorder(null);
        btnDelete.setBorderPainted(false);
        btnDelete.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnComplete1.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        btnComplete1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/tickmark.png"))); // NOI18N
        btnComplete1.setBorder(null);
        btnComplete1.setBorderPainted(false);
        btnComplete1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnComplete1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComplete1ActionPerformed(evt);
            }
        });

        btnComplete2.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        btnComplete2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/tickmark.png"))); // NOI18N
        btnComplete2.setBorder(null);
        btnComplete2.setBorderPainted(false);
        btnComplete2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnComplete2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComplete2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(221, 221, 221)
                        .addComponent(Important)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 139, Short.MAX_VALUE)
                        .addComponent(Completed))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDueDate)
                            .addComponent(lblDID, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblDueTime, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(123, 123, 123))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblCategoryName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnComplete2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnComplete1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnComplete, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(lblID))
            .addComponent(jSeparator1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Important)
                                    .addGroup(layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(lblDID)
                                                .addComponent(lblCategoryName))
                                            .addComponent(btnComplete, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(Completed))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblDueDate))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(19, 19, 19)
                                                .addComponent(lblDueTime))
                                            .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(0, 1, Short.MAX_VALUE))))
                            .addComponent(lblID))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnComplete2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnComplete1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        //JOptionPane.showMessageDialog(this, lblEventName.getText());
        EventDesc ed = new EventDesc();
        ed.setVisible(true);
        ed.txtEventName.setText(lblDID.getText());
        ed.IDDesc.setText(lblID.getText());
        ed.btnConfirm.setVisible(true);
        ed.btnUpdate.setVisible(true);
        ed.txtCategoryName.setText(lblCategoryName.getText());
        ed.cmbDD.setSelectedItem(Character.toString(lblDueDate.getText().charAt(8)) + Character.toString(lblDueDate.getText().charAt(9)));
        ed.cmbMM.setSelectedItem(Character.toString(lblDueDate.getText().charAt(5)) + Character.toString(lblDueDate.getText().charAt(6)));
        ed.cmbYYYY.setSelectedItem(Character.toString(lblDueDate.getText().charAt(0)) + Character.toString(lblDueDate.getText().charAt(1)) + Character.toString(lblDueDate.getText().charAt(2)) + Character.toString(lblDueDate.getText().charAt(3)));
        ed.cmbHours.setSelectedItem(Character.toString(lblDueTime.getText().charAt(0)) + Character.toString(lblDueTime.getText().charAt(1)));
        ed.cmbMinutes.setSelectedItem(Character.toString(lblDueTime.getText().charAt(3)) + Character.toString(lblDueTime.getText().charAt(4)));
        ed.cmbSeconds.setSelectedItem(Character.toString(lblDueTime.getText().charAt(6)) + Character.toString(lblDueTime.getText().charAt(7)));
        if (Integer.parseInt(Important.getText()) == 1)
            ed.chbImportant.setSelected(true);
    }//GEN-LAST:event_formMouseClicked

    private void btnCompleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompleteActionPerformed
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection(
                    "jdbc:mysql://localhost:3306/timekeeper", "root", "srshah");
            PreparedStatement pst = con.prepareStatement("update events set completed = 1 where ID = ?");
            pst.setInt(1, Integer.parseInt(lblID.getText()));
            pst.executeUpdate();
            this.setVisible(false);
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_btnCompleteActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection(
                    "jdbc:mysql://localhost:3306/timekeeper", "root", "srshah");
            PreparedStatement pst = con.prepareStatement("delete from events where ID = ?");
            pst.setInt(1, Integer.parseInt(lblID.getText()));
            pst.executeUpdate();
            this.setVisible(false);
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnComplete1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComplete1ActionPerformed
        int i = 0;
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection(
                    "jdbc:mysql://localhost:3306/HotelManagement", "root", "srshah");
            MainFrame.ContentPanel.removeAll();
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery("select * from rooms where hotelid =" + lblID.getText() + ";");
            while (rs.next()) {
                i = 0;
                ContentPane Panel = new ContentPane();
                Panel.setBounds(50, 50 + (i * 100), 700, 100);
                Panel.lblDID.setText(Integer.toString(rs.getInt("rID")));
                Panel.btnDelete.setVisible(false);
                Panel.btnComplete.setVisible(false);
                Panel.btnComplete1.setVisible(false);
                Panel.lblCategoryName.setText(rs.getString("Type"));
                btnComplete1.setVisible(false);
                btnComplete2.setVisible(false);
                Panel.lblDueDate.setText(rs.getString("rate"));
//                Panel.lblDueTime.setText(rs.getString("Location"));
                ContentPanel.add(Panel);
                i++;
            }
            ContentPanel.revalidate();
            ContentPanel.repaint();
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_btnComplete1ActionPerformed

    private void btnComplete2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComplete2ActionPerformed

    }//GEN-LAST:event_btnComplete2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Completed;
    public javax.swing.JLabel Important;
    public javax.swing.JButton btnComplete;
    public javax.swing.JButton btnComplete1;
    public javax.swing.JButton btnComplete2;
    public javax.swing.JButton btnDelete;
    private javax.swing.JSeparator jSeparator1;
    public javax.swing.JLabel lblCategoryName;
    public javax.swing.JLabel lblDID;
    public javax.swing.JLabel lblDueDate;
    public javax.swing.JLabel lblDueTime;
    public javax.swing.JLabel lblID;
    // End of variables declaration//GEN-END:variables
}
