/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frames;

/**
 *
 * @author RSSH
 */
public class Manager extends javax.swing.JFrame {

    /**
     * Creates new form Manager
     */
    public Manager() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainButtonBackground = new javax.swing.JPanel();
        MainMissed = new javax.swing.JButton();
        MainExit = new javax.swing.JButton();
        MainUpcoming = new javax.swing.JButton();
        MainCompleted = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MainButtonBackground.setBackground(new java.awt.Color(0, 206, 201));

        MainMissed.setBackground(new java.awt.Color(255, 255, 255));
        MainMissed.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        MainMissed.setText("Manage Login");
        MainMissed.setBorder(null);
        MainMissed.setContentAreaFilled(false);
        MainMissed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MainMissedActionPerformed(evt);
            }
        });

        MainExit.setBackground(new java.awt.Color(255, 255, 255));
        MainExit.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        MainExit.setText("EXIT");
        MainExit.setBorder(null);
        MainExit.setContentAreaFilled(false);
        MainExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MainExitActionPerformed(evt);
            }
        });

        MainUpcoming.setBackground(new java.awt.Color(255, 255, 255));
        MainUpcoming.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        MainUpcoming.setText("Manage Hotels");
        MainUpcoming.setBorder(null);
        MainUpcoming.setContentAreaFilled(false);
        MainUpcoming.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MainUpcomingActionPerformed(evt);
            }
        });

        MainCompleted.setBackground(new java.awt.Color(255, 255, 255));
        MainCompleted.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        MainCompleted.setText("Manage Rooms");
        MainCompleted.setBorder(null);
        MainCompleted.setContentAreaFilled(false);
        MainCompleted.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MainCompletedActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MainButtonBackgroundLayout = new javax.swing.GroupLayout(MainButtonBackground);
        MainButtonBackground.setLayout(MainButtonBackgroundLayout);
        MainButtonBackgroundLayout.setHorizontalGroup(
            MainButtonBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainButtonBackgroundLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(MainUpcoming, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77)
                .addComponent(MainCompleted, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addComponent(MainMissed, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(MainExit, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        MainButtonBackgroundLayout.setVerticalGroup(
            MainButtonBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainButtonBackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MainButtonBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainButtonBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(MainUpcoming, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(MainCompleted, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MainButtonBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(MainExit, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(MainMissed, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 818, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(MainButtonBackground, javax.swing.GroupLayout.PREFERRED_SIZE, 798, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 355, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(142, 142, 142)
                    .addComponent(MainButtonBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(143, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MainMissedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MainMissedActionPerformed
        int i = 0;
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection(
                "jdbc:mysql://localhost:3306/HotelManagement", "root", "srshah");
            MainFrame.ContentPanel.removeAll();
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery("select * from rooms where occupancy = 0;");
            while (rs.next()) {
                ContentPane Panel = new ContentPane();
                Panel.lblDID.setText(Integer.toString(rs.getInt("rID")));
                Panel.lblID.setText(Integer.toString(rs.getInt("rID")));
                Panel.btnDelete.setVisible(true);
                Panel.btnComplete.setVisible(false);
                Panel.btnComplete1.setVisible(false);
                Panel.btnComplete2.setVisible(false);
                Panel.lblCategoryName.setText(rs.getString("Type"));
                Panel.lblDueDate.setText(rs.getString("rate"));
                Panel.setBounds(50, 50 + (i * 100), 700, 100);
                if (i % 2 != 0) {
                    Panel.setBackground(new Color(9, 132, 227));
                }
                ContentPanel.add(Panel);
                i++;
            }
        } catch (Exception e) {
            System.out.println(e);
        }
        MainScrollPanel.setViewportView(ContentPanel);
        revalidate();
        repaint();
    }//GEN-LAST:event_MainMissedActionPerformed

    private void MainExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MainExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_MainExitActionPerformed

    private void MainUpcomingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MainUpcomingActionPerformed
        
    }//GEN-LAST:event_MainUpcomingActionPerformed

    private void MainCompletedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MainCompletedActionPerformed
        int i = 0;
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection(
                "jdbc:mysql://localhost:3306/HotelManagement", "root", "srshah");
            MainFrame.ContentPanel.removeAll();
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery("select * from rooms where occupancy = 1;");
            while (rs.next()) {
                ContentPane Panel = new ContentPane();
                Panel.lblDID.setText(Integer.toString(rs.getInt("rID")));
                Panel.lblID.setText(Integer.toString(rs.getInt("rID")));
                Panel.btnDelete.setVisible(true);
                Panel.btnComplete.setVisible(false);
                Panel.btnComplete1.setVisible(false);
                Panel.btnComplete2.setVisible(false);
                Panel.lblCategoryName.setText(rs.getString("Type"));
                Panel.lblDueDate.setText(rs.getString("rate"));
                Panel.setBounds(50, 50 + (i * 100), 700, 100);
                if (i % 2 != 0) {
                    Panel.setBackground(new Color(9, 132, 227));
                }
                ContentPanel.add(Panel);
                i++;
            }
        } catch (Exception e) {
            System.out.println(e);
        }
        MainScrollPanel.setViewportView(ContentPanel);
        revalidate();
        repaint();
    }//GEN-LAST:event_MainCompletedActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Manager().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MainButtonBackground;
    private javax.swing.JButton MainCompleted;
    private javax.swing.JButton MainExit;
    private javax.swing.JButton MainMissed;
    public javax.swing.JButton MainUpcoming;
    // End of variables declaration//GEN-END:variables
}
